// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOZ1R73pNUHPcIdk2zf0veKwUXCykv658',
    appId: '1:6246311758:web:eb0e93c792c7f81ca8601f',
    messagingSenderId: '6246311758',
    projectId: 'instagram-clone-e12f7',
    authDomain: 'instagram-clone-e12f7.firebaseapp.com',
    databaseURL: 'https://instagram-clone-e12f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'instagram-clone-e12f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3QsIgZDwFHfdEjOH5u7TVEkKYJ5hV5Og',
    appId: '1:6246311758:android:0e52c07e0ac72a9ba8601f',
    messagingSenderId: '6246311758',
    projectId: 'instagram-clone-e12f7',
    databaseURL: 'https://instagram-clone-e12f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'instagram-clone-e12f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaXqTCkFGPzP9hJIF1s6zsStaQb4ncTPQ',
    appId: '1:6246311758:ios:f7b61a87538cc2b6a8601f',
    messagingSenderId: '6246311758',
    projectId: 'instagram-clone-e12f7',
    databaseURL: 'https://instagram-clone-e12f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'instagram-clone-e12f7.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );
}
